const BLOCK_SIZE: number = 20;
const BOARD_WIDTH: number = 14;
const BOARD_HEIGHT: number = 30;
const GAME_CONTAINER_HEIGHT = BLOCK_SIZE * BOARD_HEIGHT;
const GAME_CONTAINER_WIDTH = BLOCK_SIZE * BOARD_WIDTH;

export const GAME_CONFIG = Object.freeze({
  BLOCK_SIZE,
  BOARD_WIDTH,
  BOARD_HEIGHT,
  GAME_CONTAINER_HEIGHT,
  GAME_CONTAINER_WIDTH,
});
